import faker from "faker";

const allPosts = [
    {type: "article", title: "Using React's key features", description: faker.lorem.paragraph(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: "Simple code with NodeJs", description: faker.lorem.paragraph(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "question", title: "What are simple tricks for using React hooks?", description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: "Reflux or Redux?", description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image(), notes: faker.lorem.paragraph()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "article", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
    {type: "question", title: faker.lorem.sentence(), description: faker.lorem.sentence(), image: faker.image.image()},
];

export function getAllPosts() {
    return allPosts;
}